version: "3"
services:
  database:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --innodb-buffer-pool-size=64M
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "3306:3306"
  project:
    # replace username/repo:tag with your name and image details
    image: ${IMAGE_NAME}
    container_name: ${PROJECT_NAME}
    deploy:
      #restart_policy:
        #condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 2048M
    volumes:
      - "../:/var/www/html/${PROJECT_NAME}"
      - "../docker-laravel/php.ini:/etc/php/7.1/apache2/php.ini"
      - "../docker-laravel/000-default.conf:/etc/apache2/sites-available/000-default.conf"
    ports:
      - "80:80"
      - "2222:22"
    links:
      - "database:mysql"
volumes:
  dbdata:
networks:
  default:
